# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-04 20:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoLHero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='英雄姓名')),
                ('byname', models.CharField(max_length=20, verbose_name='英雄别名')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='英雄价格')),
                ('gender', models.CharField(choices=[('girl', '女'), ('boy', '男')], default='boy', max_length=10, verbose_name='英雄性别')),
                ('type', models.CharField(blank=True, max_length=10, null=True, verbose_name='英雄类型')),
                ('is_delete', models.BooleanField(default=0, verbose_name='是否删除')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '英雄资料表',
                'verbose_name_plural': '英雄资料表',
                'db_table': 'LOLHero',
                'ordering': ['name'],
            },
        ),
    ]
