# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-10 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleinfo',
            name='image',
            field=models.ImageField(max_length=200, upload_to='article/%y/%m/%d', verbose_name='文章封面图'),
        ),
    ]
