# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-05 18:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BanClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='班级名称')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='开班时间')),
            ],
            options={
                'verbose_name': '班级信息',
                'verbose_name_plural': '班级信息',
            },
        ),
        migrations.CreateModel(
            name='CardId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=10, verbose_name='学生学号')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '学号信息',
                'verbose_name_plural': '学号信息',
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='学生姓名')),
                ('age', models.IntegerField(verbose_name='学生年龄')),
                ('gender', models.CharField(choices=[('girl', '女'), ('boy', '男')], default='boy', max_length=10, verbose_name='学生性别')),
                ('is_delete', models.BooleanField(default=0, verbose_name='是否删除')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('stuclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.BanClass', verbose_name='所属班级')),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
            },
        ),
        migrations.AddField(
            model_name='cardid',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.StudentInfo', verbose_name='所属学生'),
        ),
    ]
