# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-19 13:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='商品类别')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '商品类别信息',
                'verbose_name_plural': '商品类别信息',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.CharField(max_length=30, unique=True, verbose_name='商品编号')),
                ('goods_name', models.CharField(max_length=30, unique=True, verbose_name='商品名称')),
                ('goods_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='商品价格')),
                ('goods_image', models.ImageField(blank=True, null=True, upload_to='goods/%y/%m/%d', verbose_name='商品图片')),
                ('goods_desc', models.CharField(max_length=500, verbose_name='商品描述')),
                ('goods_num', models.IntegerField(default=0, verbose_name='商品库存')),
                ('goods_unit', models.CharField(max_length=10, verbose_name='商品单位')),
                ('goods_click', models.IntegerField(default=0, verbose_name='商品热度')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Category', verbose_name='所属类别')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
            },
        ),
    ]
