# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-16 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_orginfo_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orginfo',
            old_name='courses',
            new_name='course_num',
        ),
    ]
