# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-21 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0005_auto_20180616_1440'),
        ('orgs', '0002_auto_20180621_1148'),
    ]

    operations = [
    ]
