# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-04 11:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='学生姓名')),
                ('age', models.IntegerField(default=18, verbose_name='学生年龄')),
                ('gender', models.CharField(choices=[('girl', '女'), ('boy', '男')], default='girl', max_length=10, verbose_name='学生性别')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='学生身高')),
                ('is_delete', models.BooleanField(default=0, verbose_name='是否删除')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '学生信息表',
                'verbose_name_plural': '学生信息表',
                'db_table': 'students_info',
                'ordering': ['height'],
            },
        ),
    ]
