# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-25 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinfo',
            name='course_bull',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='课程公告'),
        ),
        migrations.AddField(
            model_name='courseinfo',
            name='need_known',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='课程须知'),
        ),
        migrations.AddField(
            model_name='courseinfo',
            name='teacher_tell',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='讲师提示'),
        ),
    ]
