# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-21 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180621_1137'),
        ('users', '0002_userprofile_is_start'),
    ]

    operations = [
    ]
