# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-06 08:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='阵营名称')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '阵营信息表',
                'verbose_name_plural': '阵营信息表',
            },
        ),
        migrations.CreateModel(
            name='EnglishName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='英文名')),
            ],
            options={
                'verbose_name': '英文名信息表',
                'verbose_name_plural': '英文名信息表',
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='英雄姓名')),
                ('byname', models.CharField(max_length=30, verbose_name='英雄别名')),
                ('gender', models.CharField(choices=[('girl', '女'), ('boy', '男')], default='boy', max_length=10, verbose_name='英雄性别')),
                ('is_delete', models.BooleanField(default=0, verbose_name='是否删除')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('hero_camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lol_hero.Camp', verbose_name='所属阵营')),
            ],
            options={
                'verbose_name': '英雄信息表',
                'verbose_name_plural': '英雄信息表',
            },
        ),
        migrations.AddField(
            model_name='englishname',
            name='hero',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lol_hero.Hero', verbose_name='所属英雄'),
        ),
    ]
