# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-21 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20180621_1002'),
        ('courses', '0003_auto_20180621_1137'),
        ('courses', '0002_auto_20180621_1148'),
    ]

    operations = [
    ]
